server:
  port: 8080
  compression:
    enabled: true
  shutdown: graceful
  undertow:
    url-charset: UTF-8
spring:
  main:
    allow-bean-definition-overriding: true
    register-shutdown-hook: true
  webclient:
    enableRequestLogging: true
    enableResponseLogging: true
    enableResponseBodyLogging: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABSE}
webclient:
  alibtrip:
    app-key: ${APP_KEY}
    app-secret: ${APP_SECRET}
    corp-id: ${CORP_ID}


